"""Add dynamic fields to daily_reports

Revision ID: 1838128e8428
Revises: a50de1dd7efd
Create Date: 2026-06-12 15:33:27.395411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from migration_utils import baseline_created_schema


# revision identifiers, used by Alembic.
revision: str = '1838128e8428'
down_revision: Union[str, Sequence[str], None] = 'a50de1dd7efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Predates ghawy_baseline: on a database built from that snapshot this
    # change is already present, so there is nothing to apply.
    if baseline_created_schema():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_reports', sa.Column('hours_worked', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('daily_reports', sa.Column('productivity', sa.Integer(), nullable=True))
    op.add_column('daily_reports', sa.Column('community_posts_count', sa.Integer(), nullable=True))
    op.add_column('daily_reports', sa.Column('members_welcomed_count', sa.Integer(), nullable=True))
    op.add_column('daily_reports', sa.Column('wins_encouraged_count', sa.Integer(), nullable=True))
    op.add_column('daily_reports', sa.Column('avg_reply_speed', sa.String(), nullable=True))
    op.add_column('daily_reports', sa.Column('platform_engagement', sa.String(), nullable=True))
    op.add_column('daily_reports', sa.Column('projects_reviewed_count', sa.Integer(), nullable=True))
    op.add_column('daily_reports', sa.Column('projects_accepted_count', sa.Integer(), nullable=True))
    op.add_column('daily_reports', sa.Column('projects_rejected_count', sa.Integer(), nullable=True))
    op.add_column('daily_reports', sa.Column('workflows_resolved_count', sa.Integer(), nullable=True))
    op.add_column('daily_reports', sa.Column('avg_resolution_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Predates ghawy_baseline: on a database built from that snapshot this
    # change is already present, so there is nothing to apply.
    if baseline_created_schema():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_reports', 'avg_resolution_time')
    op.drop_column('daily_reports', 'workflows_resolved_count')
    op.drop_column('daily_reports', 'projects_rejected_count')
    op.drop_column('daily_reports', 'projects_accepted_count')
    op.drop_column('daily_reports', 'projects_reviewed_count')
    op.drop_column('daily_reports', 'platform_engagement')
    op.drop_column('daily_reports', 'avg_reply_speed')
    op.drop_column('daily_reports', 'wins_encouraged_count')
    op.drop_column('daily_reports', 'members_welcomed_count')
    op.drop_column('daily_reports', 'community_posts_count')
    op.drop_column('daily_reports', 'productivity')
    op.drop_column('daily_reports', 'hours_worked')
    # ### end Alembic commands ###
