"""add_cf_stream_live_attendee

Revision ID: 2668e3beafa9
Revises: 
Create Date: 2026-05-29 01:45:18.203109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2668e3beafa9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'comment_reactions', ['comment_id', 'user_id'])
    op.add_column('lessons', sa.Column('cloudflare_video_id', sa.String(), nullable=True))
    op.add_column('lessons', sa.Column('video_status', sa.String(), server_default=sa.text("'pending'"), nullable=True))
    op.add_column('lessons', sa.Column('pdf_url', sa.String(), nullable=True))
    op.add_column('live_sessions', sa.Column('youtube_url', sa.String(), nullable=True))
    op.add_column('live_sessions', sa.Column('zoom_url', sa.String(), nullable=True))
    op.add_column('live_sessions', sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('live_sessions', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('live_sessions', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.alter_column('live_sessions', 'instructor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('live_sessions', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('live_sessions', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_foreign_key(None, 'live_sessions', 'users', ['created_by'], ['id'])
    # Skipped: payments FK + paypal_order_id drop (orphaned data)
    op.create_unique_constraint(None, 'post_likes', ['post_id', 'user_id'])
    op.create_unique_constraint(None, 'post_reactions', ['post_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_reactions', type_='unique')
    op.drop_constraint(None, 'post_likes', type_='unique')
    # Skipped: payments FK + paypal_order_id restore
    op.drop_constraint(None, 'live_sessions', type_='foreignkey')
    op.alter_column('live_sessions', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('live_sessions', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('live_sessions', 'instructor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('live_sessions', 'scheduled_at')
    op.drop_column('live_sessions', 'created_by')
    op.drop_column('live_sessions', 'is_published')
    op.drop_column('live_sessions', 'zoom_url')
    op.drop_column('live_sessions', 'youtube_url')
    op.drop_column('lessons', 'pdf_url')
    op.drop_column('lessons', 'video_status')
    op.drop_column('lessons', 'cloudflare_video_id')
    op.drop_constraint(None, 'comment_reactions', type_='unique')
    # ### end Alembic commands ###
