"""Add Build With Me Live models

Revision ID: 26d59cd0f46c
Revises: 3c4bcd5b2139
Create Date: 2026-05-17 03:42:45.633280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d59cd0f46c'
down_revision: Union[str, Sequence[str], None] = '3c4bcd5b2139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
