"""Add avatar_url to Guest

Revision ID: 28e6daace637
Revises: 4a329fc70371
Create Date: 2026-06-12 18:18:49.192931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from migration_utils import baseline_created_schema


# revision identifiers, used by Alembic.
revision: str = '28e6daace637'
down_revision: Union[str, Sequence[str], None] = '4a329fc70371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Predates ghawy_baseline: on a database built from that snapshot this
    # change is already present, so there is nothing to apply.
    if baseline_created_schema():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Predates ghawy_baseline: on a database built from that snapshot this
    # change is already present, so there is nothing to apply.
    if baseline_created_schema():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'avatar_url')
    # ### end Alembic commands ###
