"""add cloudflare_video_url to lessons

Revision ID: 3563232c588b
Revises: 5924afa40740
Create Date: 2026-05-30 15:10:08.422682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3563232c588b'
down_revision: Union[str, Sequence[str], None] = '5924afa40740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('cloudflare_video_url', sa.String(), nullable=True))
    op.add_column('lessons', sa.Column('is_free_preview', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'is_free_preview')
    op.drop_column('lessons', 'cloudflare_video_url')
    op.drop_column('lessons', 'description')
    # ### end Alembic commands ###
