"""legacy_emails_and_promo

Revision ID: 37f54e72ee27
Revises: 920b33de7a7e
Create Date: 2026-06-22 23:21:18.012312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f54e72ee27'
down_revision: Union[str, Sequence[str], None] = '920b33de7a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legacy_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legacy_emails_email'), 'legacy_emails', ['email'], unique=True)
    op.create_index(op.f('ix_legacy_emails_id'), 'legacy_emails', ['id'], unique=False)
    op.add_column('users', sa.Column('is_legacy_redeemed', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('users', sa.Column('subscription_source', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###

    # Insert legacy emails
    legacy_emails_table = sa.table('legacy_emails',
        sa.column('email', sa.String(255))
    )
    emails = [
        "zaineddinmohamedhassan@gmail.com", "yassineazmy12@gmail.com", "moatazahmed737@gmail.com", "medo122e@gmail.com",
        "rumashrmahjhjji@gmail.com", "om7515979@gmail.com", "omeemad111@gmail.com", "kareem.tarek12211@gmail.com",
        "khaledstfawik@hotmail.com", "ahmedesayeed32354@gmail.com", "faresyousri127@gmail.com", "maii.abdelkarim304@gmail.com",
        "amrmhamed056@gmail.com", "mohamedhag99@gmail.com", "mohamedabdellllatif1@gmail.com", "youssefmohameddessouky@gmail.com",
        "ayadidriss@gmail.com", "emazen226@gmail.com", "mohamedelsay3d0@gmail.com", "eng.mohamedezeo@gmail.com",
        "leeb09313@gmail.com", "mahmoudspeedo40@gmail.com", "eslamaskar33@gmail.com", "youssefmohammed.said.ds@gmail.com",
        "hamodi321@icloud.com", "leloabdo955@gmail.com", "ahmedyasser.js01@gmail.com", "ali.raashwan200600@gmail.com",
        "7esso252@gmail.com", "omar15.mohammed8.8@gmail.com", "amoorr55@icloud.com", "mostfamohammadrgab@gmail.com",
        "alwaleedawadab4@gmail.com", "ahmdmy2006@gmail.com", "3bdo.bassioungi@gmail.com", "aminebusiness@gmail.com",
        "t92alan@gmail.com", "hanosh5180@gmail.com", "aly1nasr0@gmail.com", "atef765hez@gmail.com",
        "ag7981277@gmail.com", "shehabehany2014@gmail.com", "alibmbozya@gmail.com", "eyadabugabal@gmail.com",
        "mennaro@gmail.com", "whopbusines1@gmail.com", "thedementry66@gmail.com", "alialaa9012@gmail.com",
        "maacandles2@gmail.com", "5920050m9hamed@gmail.com", "habebaehany071@gmail.com", "omarfawaz2003.2016@gmail.com",
        "marqiooomor@gmail.com", "abd.moh.alhashemi@gmail.com", "yousefahmed10522009@gmail.com", "amajl.con@gmail.com",
        "bassiouniiia@gmail.com", "salmakassem6@gmail.com", "akramsawers11@gmail.com", "mmna33221@gmail.com",
        "eltahahnmahmoud@gmail.com", "zizomizo.allam@gmail.com", "zaivosamy@gmail.com", "alamammydw987@gmail.com",
        "monzerlearning@gmail.com", "ahmedabdallah707io@gmail.com", "heshamabbaswork1028@gmail.com", "abdullaah.mmf@gmail.com",
        "kheba2505@gmail.com", "ahmedawmwaheed@gmail.com", "saif98mohammed77@gmail.com", "youseifmansour6@gmail.com",
        "youssefragab184@gmail.com", "marmon5123@gmail.com", "info2hazemmohamed@gmail.com", "mahmoud.abdallahh22@gmail.com",
        "yomnayoussef1@gmail.com", "abdelrahmansafwat676@gmail.com", "ziadfarg202@gmail.com", "abdallahha3aad@gmail.com",
        "ammaralie1wany@gmail.com", "mohamedrawhy4030@gmail.com", "abhw133@gmail.com", "bdalrhmneytym357@gmail.com",
        "ssarattials@gmail.com", "ssarahijazi@gmail.com", "alderman.fathy123@gmail.com", "elsoh805@gmail.com",
        "eyadasn111@gmail.com", "adm.mo7amed.09@gmail.com", "sakr66703@gmail.com", "mahmouldelbakh582@gmail.com",
        "nana6720016@gmail.com", "arwalamodi@gmail.com", "jayor955@gmail.com", "mark.gouda.farah@gmail.com",
        "hamidelsadig25@gmail.com", "mwaled507@gmail.com", "mo7amad.osama.29@gmail.com", "tarhgf359@gmail.com",
        "adamarrfayek2018@gmail.com", "youssef.egy321@gmail.com", "ms1963710@gmail.com", "skoskoskop121@gmail.com",
        "mohamedahmed243171@gmail.com", "emona9412@gmail.com", "youssefbassem@aucegypt.edu", "ohoon.alhousani@gmail.com",
        "abdallahlearn2day@gmail.com", "hamidelsadig23@gmail.com", "ameenabu2016@gmail.com", "abdullahabouafia@gmail.com",
        "aboodalbanaa4871@gmail.com", "ragabkareem878@gmail.com", "mustafabadawi48@gmail.com", "adamloay265@gmail.com",
        "mohamedatia16max@gmail.com", "abdoegypt001@gmail.com", "ziyadsaleh764@gmail.com", "habebawafa@gmail.com",
        "sh30117661@gmail.com", "nairaosama563@gmail.com", "bdalrhmnnasrahmad84@gmail.com", "alwaheadahmed@gmail.com",
        "monamohsen529@gmail.com", "omarcodemakhtar@gmail.com", "tassneemmohamad@gmail.com", "alaamahm449@gmail.com",
        "mazen.elteer123@gmail.com", "farha.fahmy92@gmail.com", "mostafaahmad010993940131@gmail.com", "ahmedabdullah01501201521@gmail.com",
        "yarahossam331@gmail.com", "mohamepxd@gmail.com", "amale7397@gmail.com", "m7tdrt6shx@privaterelay.appleid.com",
        "ahmedmohamadrabie@gmail.com", "dinamahmoudkhalil21@gmail.com", "ziadabdelnasser21@gmail.com", "ibrahemostfasuid@gmail.com",
        "aboelrosabdo601@gmail.com", "yoyoashraf2003@gmail.com", "podytamer22@gmail.com", "jjyss4dnzx@privaterelay.appleid.com",
        "m.elsayed1803@gmail.com", "ahmed72abdullh@gmail.com", "hammagua7@gmail.com", "fayeklobad@gmail.com",
        "elfoouliomar@gmail.com", "mahmoud.sherpini@gmail.com", "mdinaahassan1999@gmail.com", "novasparke43@gmail.com",
        "elzayat194@gmail.com", "adhmahmad500@gmail.com", "ywael1333@gmail.com", "yroro7935@gmail.com",
        "habibaaibrahim7279@gmail.com", "nadaabdlali@gmail.com", "abdelrahmanebrahim2007@gmail.com", "haagerali669@gmail.com",
        "belalaliva99@gmail.com", "mhmedmahmoud213@icloud.com", "ahmed.diab24@outlook.com", "ramy.wadina@gmail.com",
        "abdohussien85@gmail.com", "mmohamedsayed7811@gmail.com", "adhamh120@gmail.com", "om13332008@gmail.com",
        "mohamedd.salah21@gmail.com", "omaraldel13332008@icloud.com", "hmerawed@gmail.com", "mohamedamrahmed2005@gmail.com",
        "esame9999@icloud.com", "logym9393@gmail.com", "lilmerasoliman1@gmail.com", "adhamnassar0192@gmail.com",
        "a.7ussien2013@gmail.com", "seif.personal18@gmail.com", "mohamedatia30881@gmail.com", "fatimaabullnaga1@gmail.com",
        "mohamedhashem1995@gmail.com", "mhmudara@gmail.com", "shmsshshow@gmail.com", "baselmasry050@gmail.com",
        "khaled.o3111@yahoo.com", "mostafa.mahmoud.bui@gmail.com", "adhamabdelaziz100@gmail.com", "ymtawfik04@gmail.com",
        "xxxomar.ahmed.2024@gmail.com", "ranooshsidid@gmail.com", "seif01062433721@gmail.com", "antonyrefaat71@gmail.com",
        "kaly0260@gmail.com", "nada.ahmadgomaa112@gmail.com", "jannamahmond512@gmail.com", "ahmedhasan4006@gmail.com",
        "nodasad@gmail.com", "omaraldly20@gmail.com", "saedalo851@gmail.com", "qjqwfxxf7g@privaterelay.appleid.com",
        "iyadmohammed70@gmail.com", "ismailhamdy1234@gmail.com", "adam.nasr37007@gmail.com", "youssef72002@gmail.com",
        "zeyadz666@gmail.com", "minagorge741@gmail.com", "contact@hanishaker.net", "melmatmohamed@gmail.com",
        "drhadyyy@gmail.com", "kirolsksaymirbyb@gmail.com", "haechan62@gmail.com", "eladawyeyad01@gmail.com",
        "raneya-mohamed@hotmail.com", "fatmabusiness03@gmail.com", "officicalahmadmedhat@gmail.com", "abdelrhmanahmadz253@gmail.com",
        "silenttwraith@gmail.com", "mm820247@gmail.com", "ahmedkhaledhmahmoud2022@gmail.com", "anasayoub15a@gmail.com",
        "yossefamed50@gmail.com", "mh143100@gmail.com", "dr.ahmedhassaninfo@gmail.com", "alomda552005@gmail.com",
        "rebrahemenelbadrry@gmail.com", "abduols.qtr@hotmail.com", "rwmanybshay9@gmail.com", "1.amaar1.yasser@gmail.com",
        "2guysgourse@gmail.com", "ahmed.adel20061116@gmail.com", "komar7867@gmail.com", "shokr821@gmail.com",
        "engx7moning@gmail.com", "mahmoudgmal700@gmail.com", "yassiin2099@gmail.com", "el43rawy21@gmail.com",
        "mm.salah937@gmail.com", "slammhmadhad1@gmail.com", "jna98414@gmail.com", "amrmazen1111@gmail.com",
        "ahmedhamada777202020@gmail.com", "mohamedkamal21000@gmail.com", "monamhossam93@gmail.com", "minaamir1217@gmail.com",
        "elbashmohandas01@gmail.com", "nahl6@yahoo.com", "youssefkhaledgamal.8@gmail.com", "mero.com821@gmail.com",
        "mynaeshhat51@gmail.com", "twang2002@gmail.com", "hamada.eissa20@gmail.com", "abdelrahmanamr1623@gmail.com",
        "fcjfjc8@gmail.com", "nouranbackup17@gmail.com", "muhammad.awwad.077@gmail.com", "mustafakhaled6663@gmail.com",
        "mennael-gazaar812@gmail.com", "mohamednourbeef0@gmail.com", "abdelhameed1267@gmail.com", "solimanomar011@gmail.com",
        "mtifa58@gmail.com", "rnda.zakarya@gmail.com", "alimohamedgawish7@gmail.com", "bedo.1410k@gmail.com",
        "khalilnadirhassan@gmail.com", "amrzarzore@gmail.com", "loaymohamed606@gmail.com", "ahmadali002011198@gmail.com",
        "ahmedamagady4@gmail.com", "khedrmahmoud392@gmail.com", "arwaaamohamed535@gmail.com", "engineermr40@gmail.com",
        "salmamansour022@gmail.com", "omradasolo@gmail.com", "farahos131@gmail.com", "aserzaghloul2009@gmail.com",
        "ib2945585@gmail.com", "mohaad11@icloud.com", "omralhrw@gmail.com", "baahote167@gmail.com",
        "shesmaaal4444@gmail.com", "esraanwar265@gmail.com", "omafelky_98@hotmail.com", "ffjrallanazi@gmail.com",
        "mostafaotfy28social@gmail.com", "adamwafaey2006@gmail.com", "mooaboelezz74@gmail.com", "damasomaa2@gmail.com",
        "alisahaban363@gmail.com", "karimelgendy@gmail.com", "anasahmedsahban210@gmail.com", "s011224268477@gmail.com",
        "zeyadtamer146@gmail.com", "moaz.khaled10@gmail.com", "amlalmarian@gmail.com", "abdalmrhmandiaaeeldeen@gmail.com",
        "rana.gamal905@gmail.com", "41itqan20@gmail.com", "karimhisham1210@gmail.com", "omarzzz579@gmail.com",
        "muhammedabdelghani@gmail.com", "rami.alaa-eldin@outlook.com", "engpeter91@gmail.com", "7azoka2004@gmail.com",
        "mkea619766@gmail.com", "q82024445@gmail.com", "3bs9sim@gmail.com", "mohamed.mehrez@gmail.com",
        "omarelbialy@gmail.com", "alaa.saalah790@gmail.com", "ahk223@gmail.com", "zxc50zxcc@gmail.com",
        "ahmedmansour2101@gmail.com", "sherinhossam7@gmail.com", "amr13241324@gmail.com", "kerollosmagdy00@gmail.com",
        "msm4allgpt@gmail.com", "mohamednasardesouky@gmail.com", "sleem.star6764@gmail.com", "saraab331@protonmail.com",
        "aboaihamed@gmail.com", "ahmed01033774549@gmail.com", "rabie.r112233@gmail.com", "nirmenahmad97@gmail.com",
        "abelraahman134200@gmail.com", "mohamoed3zma77@gmail.com", "b.1s2@hotmail.com", "zhawwsad@gmail.com",
        "oelshazli22@gmail.com", "m92taz@gmail.com", "body.gogo666@gmail.com", "wbdalwahd50@gmail.com",
        "epsf.hue.lailas@gmail.com", "engmsmujahid@gmail.com", "anasxxxxzzzj2009@gmail.com", "haneenmashehata@gmail.com",
        "abdallhala246@gmail.com", "mazennawar10@gmail.com", "wekenzil1995@gmail.com", "4v9nnkzdcd@privaterelay.appleid.com",
        "mrhabola@gmail.com", "mostafakamael122000@gmail.com", "mostafa.nonne@gmail.com", "karimmohmoud7@gmail.com",
        "abanooukamael133@gmail.com", "eyad.azzab@gmail.com", "moazh3109@gmail.com", "halabouflah2001@gmail.com",
        "raouofmohamad@gmail.com", "ahmd.tammer8806@gmail.com", "ala7781@gmail.com", "hosssam.programs@outlook.com",
        "mahmoudhesham7763@gmail.com", "ys684993@gmail.com", "markrokakoko@gmail.com", "ansmarzouk411@gmail.com",
        "alyelfouely77@gmail.com", "rababhosny065@gmail.com", "gamalomhamed7140@gmail.com", "moaz.shakar2021@gmail.com",
        "mariamwael742007@gmail.com", "omarmohamedal.official02@gmail.com", "seifeldeenemaby@gmail.com", "hamadatark045@gmail.com",
        "ahmedamer2004200@gmail.com", "hayaazab8@gmail.com", "mohamedselim14286@gmail.com", "fariselghazaly2@gmail.com",
        "pdgpjx9292@privaterelay.appleid.com", "hafozaahazomm@gmail.com", "mahmoudmostfa745@gmail.com", "shimaaelsayed891@gmail.com",
        "omar.elqabbany@gmail.com", "mmanan84@gmail.com", "ya0643421@gmail.com", "kamalasaad1991@gmail.com",
        "ahmedfawzyyyy444@gmail.com", "sleembanob70@gmail.com", "enigma.s.pearl@gmail.com", "omarahmed363d@gmail.com",
        "a7med.osama3712@gmail.com", "ahah6hah@gmail.com", "enghussmoo@gmail.com", "mstfymhmwdmstfy856@gmail.com",
        "abdelrahmanserver@gmail.com", "wjqf9btygg4@privaterelay.appleid.com", "marwan.sbiika@icloud.com", "mazenramy6oct@gmail.com",
        "azooooz1411@hotmail.com", "haker3000haker3000@gmail.com", "ahmedalbahar98@gmail.com", "aata7188@gmail.com",
        "lwy952645@gmail.com", "aboyouniseelkashe@gmail.com", "mohcr7392@gmail.com", "mohamedhassanr18@gmail.com",
        "aa886598@gmail.com", "hamzainm89@gmail.com", "malekdawoodd@gmail.com", "ahmedpro518@gmail.com",
        "megomohamedn@gmail.com", "eyadsadawe11@gmail.com", "mazenssam3@gmail.com", "papernshhopgiga@gmail.com",
        "youssefahary77@gmail.com", "omarashrftaha19@gmail.com", "karim.a.eldidi@gmail.com", "hm8087022@gmail.com",
        "muhamedhanyyy0099@gmail.com", "son.n8n@gmail.com", "hema01973@gmail.com", "bamarhool82@gmail.com",
        "anas.shmeeem@gmail.com", "maha.a.a.osman@gmail.com", "ahmedwork2304@gmail.com", "mohamedmabd183@gmail.com",
        "om37160030@gmail.com", "mahmoudahmed1928n@gmail.com", "karimshady911@gmail.com", "karasy305@gmail.com",
        "yassintahri109@gmail.com", "d4ym692bhx@privaterelay.appleid.com", "ebrahemmohameeyousef@gmail.com", "sayedayman1810@gmail.com",
        "hamidaemmar870@gmail.com", "1alnnatour102@gmail.com", "bluesky2527199@gmail.com", "mostafamunir7@gmail.com",
        "teamaomr82@yahoo.com", "a.gad@nu.edu.eg", "hozifacf5@gmail.com", "raniamoustafa288@gmail.com",
        "raniamoustafa307@gmail.com", "yasmin.reda2010@gmail.com", "mariaremos7edky@gmail.com", "karawanshaqiah@gmail.com",
        "mazenmo906@gmail.com", "mariamelelshihawy716@gmail.com", "zeyadossama94@gmail.com", "abudalia2015ma@gmail.com",
        "amrprince739@gmail.com", "felbarnshawy@gmail.com", "forevertwins348@gmail.com", "parthinianessim@gmail.com",
        "apdoosalama555@gmail.com", "lokaelgammal122@gmail.com", "bodyroogy00@gmail.com", "hodaelewa99@gmail.com",
        "ahmedf2010ooo@gmail.com", "ahmed.aa77198@gmail.com", "7p9j52mt8f@privaterelay.appleid.com", "judy.ramy4321@gmail.com",
        "mohamedahzem20052005@gmail.com", "fathy.saeed.elmekwy@gmail.com", "hand.media.ads@gmail.com", "remon.u.marzok@gmail.com",
        "saadenkahledmohamedabdo@gmail.com", "amir-gamal@hotmail.com", "moh.sherif2777@gmail.com", "ans370124@gmail.com",
        "anassfeller@gmail.com", "adhamgoo2011@gmail.com", "amrk77686@gmail.com", "uuuuyiii8@gmail.com",
        "yousefleshishtwy30@gmail.com", "ahmed.y00er@gmail.com", "malekalgammal@gmail.com", "mohammedsafwat479@gmail.com",
        "2006yooesf@gmail.com", "yousefayman060@gmail.com", "elshoukyeslam@gmail.com", "y.abdelwahab110@gmail.com",
        "alsydasma887@gmail.com", "mahmouds011224268847@gmail.com", "am205210@gmail.com", "mohamedkhaledpro23122@gmail.com",
        "zeyad1932002@gmail.com", "ahmedq8m3@gmail.com", "halaellythe2006@gmail.com", "gml1234567891011@gmail.com",
        "omar2006hamza@gmail.com", "sotaher45@gmail.com", "elsheikhomhamed105@gmail.com", "afnan.abdullah.2028@gmail.com",
        "rokiakotb7@gmail.com", "sahoma4434@gmail.com", "abdallahalbana105@gmail.com", "zahrafaorghaly1@gmail.com",
        "nabil.ahmed123x@gmail.com"
    ]
    op.bulk_insert(legacy_emails_table, [{'email': email} for email in emails])

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_source')
    op.drop_column('users', 'is_legacy_redeemed')
    op.drop_index(op.f('ix_legacy_emails_id'), table_name='legacy_emails')
    op.drop_index(op.f('ix_legacy_emails_email'), table_name='legacy_emails')
    op.drop_table('legacy_emails')
    # ### end Alembic commands ###
