"""Update Guest of Honors models

Revision ID: 4a329fc70371
Revises: 1838128e8428
Create Date: 2026-06-12 17:32:44.505011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a329fc70371'
down_revision: Union[str, Sequence[str], None] = '1838128e8428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest_sessions', sa.Column('platform', sa.String(), nullable=True))
    op.add_column('guest_sessions', sa.Column('session_url', sa.String(), nullable=True))
    op.add_column('guest_sessions', sa.Column('attendees_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('guest_sessions', sa.Column('rating', sa.Numeric(precision=3, scale=1), server_default=sa.text('0.0'), nullable=True))
    op.drop_column('guest_sessions', 'attendees')
    op.drop_column('guest_sessions', 'video_url')
    op.drop_column('guest_sessions', 'duration_minutes')
    op.add_column('guests', sa.Column('avatar_initials', sa.String(length=5), nullable=True))
    op.add_column('guests', sa.Column('avatar_color', sa.String(length=20), nullable=True))
    op.add_column('guests', sa.Column('sessions_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('guests', sa.Column('attendees_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.drop_column('guests', 'total_sessions')
    op.drop_column('guests', 'company_logo')
    op.drop_column('guests', 'avatar_url')
    op.drop_column('guests', 'total_attendees')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('total_attendees', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('guests', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('guests', sa.Column('company_logo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('guests', sa.Column('total_sessions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_column('guests', 'attendees_count')
    op.drop_column('guests', 'sessions_count')
    op.drop_column('guests', 'avatar_color')
    op.drop_column('guests', 'avatar_initials')
    op.add_column('guest_sessions', sa.Column('duration_minutes', sa.INTEGER(), server_default=sa.text('60'), autoincrement=False, nullable=True))
    op.add_column('guest_sessions', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('guest_sessions', sa.Column('attendees', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_column('guest_sessions', 'rating')
    op.drop_column('guest_sessions', 'attendees_count')
    op.drop_column('guest_sessions', 'session_url')
    op.drop_column('guest_sessions', 'platform')
    # ### end Alembic commands ###
