"""add phone_otps table

Revision ID: 87f82a1e494e
Revises: e478012af2b4
Create Date: 2026-06-01 03:42:24.184040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from migration_utils import baseline_created_schema
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87f82a1e494e'
down_revision: Union[str, Sequence[str], None] = 'e478012af2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Predates ghawy_baseline: on a database built from that snapshot this
    # change is already present, so there is nothing to apply.
    if baseline_created_schema():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'markers')
    op.drop_column('lessons', 'cloudflare_video_id')
    op.drop_column('lessons', 'cloudflare_video_url')
    op.drop_column('user_progress', 'current_time')
    op.drop_column('user_progress', 'is_completed')
    op.drop_column('user_progress', 'updated_at')
    op.drop_column('user_progress', 'watched_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Predates ghawy_baseline: on a database built from that snapshot this
    # change is already present, so there is nothing to apply.
    if baseline_created_schema():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('watched_percent', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    op.add_column('user_progress', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('user_progress', sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('user_progress', sa.Column('current_time', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    op.add_column('lessons', sa.Column('cloudflare_video_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lessons', sa.Column('cloudflare_video_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lessons', sa.Column('markers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
