"""resync legacy_emails to the real Atlas roster

Revision ID: a7f1c93d20b4
Revises: f5a6b7c8d9e0
Create Date: 2026-08-28 00:00:00.000000

`legacy_emails` was seeded in 37f54e72ee27 from a corrupted transcription of the
Whop export, and nobody noticed because the failure is silent from the outside:
the page just answers "هذا البريد غير مؤهل للعرض" and the member assumes they
were never on the list.

Diffing the 489 seeded rows against the 488 unique addresses in the export:

  * 173 of the 488 real Atlas members are not in the table at all — 171 of them
    only as a misspelling of their address, 2 missing outright.
  * 171 table rows are misspellings with no counterpart in the export.

So better than a third of Atlas was refused throughout round 1 no matter what
they typed, because the address being checked against was not theirs.

This migration makes the table the roster: 491 addresses — the 488 from the
export plus the 3 rows already in the table that the export has no counterpart
for, which are kept rather than guessed at.

Two columns come with it:

  * legacy_emails.full_name — the announcement email greets the member by name,
    and a list of bare addresses cannot do that.
  * users.legacy_promo_round — which round of the promo an account has spent.
    is_legacy_redeemed stays as the historical record and is never cleared;
    the round number is what reopens the offer, so bumping ATLAS_PROMO_ROUND in
    app/routers/atlas.py is the whole switch and no flag anywhere needs
    resetting. Existing redeemers are backfilled to round 1.

The roster is embedded as a literal, the same way 37f54e72ee27 embedded its
list — a migration must produce the same result forever, so it cannot go and
read a spreadsheet at upgrade time.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from migration_utils import baseline_created_schema


# revision identifiers, used by Alembic.
revision: str = 'a7f1c93d20b4'
down_revision: Union[str, Sequence[str], None] = 'f5a6b7c8d9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# (email, full_name) — the 488 unique addresses from the "AI Automation Atlas"
# Whop export plus the 3 pre-existing rows with no counterpart in it. Names are
# the export's `Customer Name`; None where the export has none. A handful were
# stored mojibake'd (UTF-8 Arabic read as cp1256) and are repaired here.
ATLAS_ROSTER: list[tuple[str, str | None]] = [
    ('1.amaar1.yasser@gmail.com', 'Amaar Yasser hamdy'),
    ('1alnatour102@gmail.com', 'Hassan'),
    ('2006yoeesf@gmail.com', 'Youssef helmy'),
    ('2guyscourse@gmail.com', 'Mohamed Salah'),
    ('3bdo.bassiouni@gmail.com', 'طارق بسيونى'),
    ('3bs9sim@gmail.com', 'Abdelrahman Nader'),
    ('41itqan20@gmail.com', 'Ali Amr'),
    ('4v9nnkzdcd@privaterelay.appleid.com', 'Mohamed Mostafa'),
    ('592005m9hamed@gmail.com', 'mohamed emad'),
    ('7azoka2004@gmail.com', 'Mostafa hesham abdallah saad Morgan'),
    ('7esso252@gmail.com', 'hesso'),
    ('7p9j52mt8f@privaterelay.appleid.com', None),
    ('a.7ussien2013@gmail.com', 'Ahmed Hussien'),
    ('a.gad@nu.edu.eg', 'Abdelrahmangad'),
    ('a7med.osama3712@gmail.com', 'Ahmed Osama'),
    ('aa8886598@gmail.com', 'Ahmed Abdo'),
    ('aata7188@gmail.com', 'Ahmed ata'),
    ('abanoubkamal133@gmail.com', 'Abanoub Kamal'),
    ('abd.moh.alhashemi@gmail.com', 'AbdullahAlameer'),
    ('abdallaalbana105@gmail.com', 'abdalla albana'),
    ('abdallaha3aad@gmail.com', 'Abdallah asaad'),
    ('abdallahlearn2day@gmail.com', 'Legend.A'),
    ('abdallhalaa246@gmail.com', 'Abdallah Alaa'),
    ('abdallhelzayat194@gmail.com', 'Abdullah Elzayat'),
    ('abdalrhmandiaaeldeen@gmail.com', 'Abdalrhman Diaa'),
    ('abdelhameed1267@gmail.com', 'Abdelhamid Mahmoud'),
    ('abdelrahmanamr1623@gmail.com', 'Abdelrahamn Amr'),
    ('abdelrahmanebrahim2007@gmail.com', 'Abdelrahman'),
    ('abdelrahmansafwat676@gmail.com', 'Abdelrahman Safwat'),
    ('abdelrahmanserver@gmail.com', 'Abdelrahman rabea fathy abdellatif'),
    ('abdelrhmanahmedz253@gmail.com', 'Abdelrahman ahmed abdelaziz'),
    ('abdoegypt001@gmail.com', 'Abdelrahman'),
    ('abdohussien85@gmail.com', 'abdohussien7f'),
    ('abdullah.mmf@gmail.com', 'Abdullah'),
    ('abdullahaboafiawork@gmail.com', 'Abdullah Aboafia'),
    ('abduls.qtr@hotmail.com', None),
    ('abelrahman1342008@gmail.com', 'Abdelrahman Saleh'),
    ('abhw133@gmail.com', 'Abdelrahman Harbi'),
    ('aboaihamdhamzamahmoud123@gmail.com', 'Hamza Mahmoud Abo El Hamd'),
    ('aboaihamed@gmail.com', None),
    ('aboelrosabdo601@gmail.com', 'Abdo Aboelros'),
    ('aboodalbana4871@gmail.com', 'abdalla albana'),
    ('aboyouniiselkaseh@gmail.com', 'Younis'),
    ('abudalia2015ma@gmail.com', None),
    ('adam.nasr37007@gmail.com', 'Adam Nasr'),
    ('adamamrfayek2018@gmail.com', 'Adam Amr fayek'),
    ('adamloay265@gmail.com', 'Adam Loay'),
    ('adamwafaey2006@gmail.com', 'adam zaky'),
    ('adhamabdelaziz100@gmail.com', 'Adham Abdelaziz'),
    ('adhamgoo2011@gmail.com', 'adhamgo'),
    ('adhamh120@gmail.com', 'Adham Hassan'),
    ('adhamnassar0192@gmail.com', 'Adham Ahmed Nassar'),
    ('adhmahmed500@gmail.com', 'Adham l domzz'),
    ('adm.mo7amed.09@gmail.com', 'Adam Mohamed'),
    ('afnan.abdullah.2028@gmail.com', None),
    ('ag7981277@gmail.com', 'Ali Gaber'),
    ('ahah6hah@gmail.com', 'Amr'),
    ('ahk223@gmail.com', 'ahk223'),
    ('ahmadali002011980@gmail.com', 'Ahmed Ali mahmoud abosoud'),
    ('ahmdmy2006@gmail.com', 'Ahmed Wagdy'),
    ('ahmed.aa771988@gmail.com', 'AHMED MAHROUS'),
    ('ahmed.adel20061116@gmail.com', 'ahmed adel'),
    ('ahmed.diab24@outlook.com', 'Ahmed Abdullah Diab Mohamed'),
    ('ahmed.tamer8806@gmail.com', 'Ahmed tamer'),
    ('ahmed.y00er@gmail.com', 'Ahmed Yasser'),
    ('ahmed01033774549@gmail.com', 'Ahmed Amin'),
    ('ahmed72abdullh@gmail.com', 'Ahmed Abdullah'),
    ('ahmedabdallah707io@gmail.com', 'Ahmed Abdallah'),
    ('ahmedabdullah015012015@gmail.com', 'Ahmed Abdullah (الحرامي)'),
    ('ahmedalbahar98@gmail.com', 'Ahmed Elbahar'),
    ('ahmedamer20042007@gmail.com', 'Ahmed Amer'),
    ('ahmedamgady4@gmail.com', 'Ahmed magdy'),
    ('ahmedawmwaheed@gmail.com', 'Ahmed Waheed'),
    ('ahmedelsayed32354@gmail.com', 'Ahmed'),
    ('ahmedf2010ooo@gmail.com', None),
    ('ahmedfawzyyy444@gmail.com', 'Ahmed fawzy'),
    ('ahmedhamada7772020@gmail.com', 'Ahmed Hamada'),
    ('ahmedhassan4006@gmail.com', 'Ahmed hassan'),
    ('ahmedkhaledmahmoud2022@gmail.com', 'Ahmed Khaled mahmoud'),
    ('ahmedmansour2101@gmail.com', 'AHMED Mansour'),
    ('ahmedmohammadrabie@gmail.com', 'Ahmed Mohamed Rabie metwally ahmed'),
    ('ahmedpro518@gmail.com', 'Ahmed Mohamed Salah Eldin Alhanafawy'),
    ('ahmedq8m3@gmail.com', 'Ahmed Sulaiman'),
    ('ahmedwork2304@gmail.com', 'Ahmed Mohammed'),
    ('ahmedyasser.js01@gmail.com', 'Ahmed yasser'),
    ('akramsawers11@gmail.com', 'Akram Maher'),
    ('ala7781@gmail.com', 'Alaa Hijawi'),
    ('alaa.saalah790@gmail.com', 'Alaa Salah Ahmed Mohamed'),
    ('alaamahm449@gmail.com', 'alwa'),
    ('alamammydw987@gmail.com', 'Mohamed Medo'),
    ('albotiaa@gmail.com', 'AbdulAlboti'),
    ('alderman.fathy123@gmail.com', 'Abderhman fathy'),
    ('ali.rashwan200600@gmail.com', 'Aly Rashwan'),
    ('alialaa9012@gmail.com', 'Ali Alaa'),
    ('alibmbozya@gmail.com', 'Ali Bmbozya'),
    ('alimohamedgawish7@gmail.com', 'Ali mohamed gawish'),
    ('alishaban363@gmail.com', 'Ali mohamed shaaban'),
    ('alomda552005@gmail.com', 'Abdalla Mamdouh'),
    ('alsydasma887@gmail.com', 'Asmaa Elsayed'),
    ('alwahediahmed@gmail.com', 'Ahmed'),
    ('alwaleedawadab4@gmail.com', 'Alwaleed'),
    ('aly1nasr0@gmail.com', 'ziad nasr'),
    ('alyelfouly77@gmail.com', 'Aly elfouly'),
    ('am2052105@gmail.com', 'ibrahim mohammed'),
    ('amajl.con@gmail.com', 'Abdulrahman Riyad'),
    ('amale7397@gmail.com', 'Amal Elsayed'),
    ('ameenabu2016@gmail.com', 'Ameen Abu Alnasser'),
    ('aminebusinness@gmail.com', 'Amine'),
    ('amir-gamal@hotmail.com', 'Amir abdelmalek'),
    ('amlalmariam@gmail.com', 'mariam amlal'),
    ('ammaralielwany@gmail.com', 'ammaralielwany@gmail.com'),
    ('amoorr55@icloud.com', 'Omar'),
    ('amr13241324@gmail.com', 'Amr Shaker'),
    ('amrk77686@gmail.com', 'amrk48'),
    ('amrmazen1111@gmail.com', 'Mazen Amr'),
    ('amrmhamed056@gmail.com', 'Amr Mohamed'),
    ('amrprince739@gmail.com', None),
    ('amrzarzore@gmail.com', 'Amr Khaled'),
    ('anas.shmeem@gmail.com', None),
    ('anasahmedshaban210@gmail.com', 'Anas Ahmed shaban'),
    ('anasayoub15a@gmail.com', 'Anas Ayoub'),
    ('anassfeller@gmail.com', None),
    ('anasxxxzzzz2009@gmail.com', 'Anas Ahmed'),
    ('ans370124@gmail.com', 'Anas soliman'),
    ('ansmarzouk411@gmail.com', 'Anas Mohamed Marzouk'),
    ('antonyrefaat71@gmail.com', 'Tony refaat'),
    ('apdoosalama555@gmail.com', 'Abdelrahman Salama'),
    ('arwaamohamed535@gmail.com', 'Arwaa Mohamed tayel'),
    ('arwalamoudi@gmail.com', 'Arwa'),
    ('aserzaghloul2009@gmail.com', 'Asser zaghloul'),
    ('atef765hez@gmail.com', 'Atef mahmoud'),
    ('ayadidriss@gmail.com', 'Ayad'),
    ('azooooz1411@hotmail.com', 'Abdualziz'),
    ('b.1s2@hotmail.com', 'b.1s'),
    ('bahote167@gmail.com', 'Mostafa Abdelhamid'),
    ('bamarhool82@gmail.com', 'Ahmed bamarhool'),
    ('baselelmasry050@gmail.com', 'basel elmasry'),
    ('bassiouniia@gmail.com', 'Abdelrahman Bassiounii'),
    ('bdalrhmnhythm357@gmail.com', 'عبدالرحمن هيثم'),
    ('bdalrhmnnasrahmd84@gmail.com', 'Abdelrahman naser'),
    ('bedo.1410k@gmail.com', 'Mohamed Ahmed Salem'),
    ('belalaliva99@gmail.com', 'Belal'),
    ('bluesky25271995@gmail.com', 'Sama Ali'),
    ('body.gogo666@gmail.com', 'Elsolia'),
    ('bodyrogy00@gmail.com', 'Abdelrahman Waleed'),
    ('contact@hanishaker.net', 'Hany Shaker'),
    ('d4ym692bhx@privaterelay.appleid.com', 'Mostafa'),
    ('damasomaa2@gmail.com', 'Mahmoud Farouq'),
    ('dinamahmoudkhalil21@gmail.com', 'Dina Mahmoud Khalil'),
    ('dr.ahmedhassaninfo@gmail.com', 'Ahmed Hassan'),
    ('drhadyyy@gmail.com', 'Ahmed M Abdelhady Mahdy'),
    ('ebrahemmohamedyousef@gmail.com', 'Ebrahem Mohamed'),
    ('el43rawy21@gmail.com', 'Youssef gamal'),
    ('eladawyeyad01@gmail.com', 'Eyad Mohamed'),
    ('elbashmohandes01@gmail.com', 'Ahmed hussein'),
    ('elfouliomar@gmail.com', 'Omar Elfouli'),
    ('elsheikhmohamed105@gmail.com', 'Mohamed Elsheikh'),
    ('elshoukyeslam@gmail.com', None),
    ('elsoh805@gmail.com', 'hossam ahmed'),
    ('eltahhanmahmoud@gmail.com', 'Mahmoud eltahhan'),
    ('emazen226@gmail.com', 'Mazen ehab bakr'),
    ('emona9412@gmail.com', 'Mona Ebrahim'),
    ('eng.mohamedezo@gmail.com', 'mohamed ezo'),
    ('enghussmo@gmail.com', 'Moustafa Hussein abdelatif hussien'),
    ('engineermr40@gmail.com', 'Ahmed Souody'),
    ('engmsmujahid@gmail.com', 'Mohamed Megahed'),
    ('engpeter91@gmail.com', 'Peter Gaed'),
    ('engx7moning@gmail.com', 'Mustafa mahmoud Al-Hadidi'),
    ('enigma.s.pearl@gmail.com', 'hi friends'),
    ('epsf.hue.lailas@gmail.com', 'Laila A Elhefnawy'),
    ('esame9999@icloud.com', 'Mohamed'),
    ('eslamaskr33@gmail.com', 'ESLAM HANY SAMIR ASKR'),
    ('esraaanwar265@gmail.com', 'Esraa Anwar abdelaziz'),
    ('eyad.azzab@gmail.com', 'Eyad Azab'),
    ('eyadabugabal@gmail.com', 'Eyad AbuGabal'),
    ('eyadasn111@gmail.com', 'EYAD TECNO'),
    ('eyadsadawe11@gmail.com', 'Eyad Ahmed'),
    ('farahos131@gmail.com', 'Farah Osama Mohamed'),
    ('faresyousri127@gmail.com', 'Marsh'),
    ('farha.fahmy92@gmail.com', 'Farha Fahmy Raafat'),
    ('fariselghazaly2@gmail.com', 'Faris El-Ghazaly'),
    ('fathy.saeed.elmekawy@gmail.com', None),
    ('fatimaabulnaga1@gmail.com', 'fatimaabulnaga5d'),
    ('fatmabusiness03@gmail.com', 'Fatma'),
    ('fayeklobad@gmail.com', 'fayek mohamed fayek abbas hessen lobad'),
    ('fcjfjc8@gmail.com', 'bilal hassan ali'),
    ('felbarnshawy@gmail.com', None),
    ('ffajralanazi@gmail.com', 'fajr al anzi'),
    ('forevertwins348@gmail.com', None),
    ('gamalmohamed7140@gmail.com', 'Gamal Othman Mohamed'),
    ('gml1234567891011@gmail.com', 'Gemy'),
    ('haageralii669@gmail.com', 'Hager Ali'),
    ('habebahany071@gmail.com', 'Habeba Hany Refeat'),
    ('habebawafa@gmail.com', 'Habiba Wafa'),
    ('habibaibrahim7279@gmail.com', 'Habiba Ibrahim'),
    ('haechanj62@gmail.com', 'Jihad Ayman'),
    ('hafozaahazomm@gmail.com', 'Youssef hafez'),
    ('haker3000haker3000@gmail.com', None),
    ('halaboufellah2001@gmail.com', 'Hala Boufellah'),
    ('halaellythe2006@gmail.com', 'Hla Ellythe'),
    ('hamada.eissa20@gmail.com', 'Mohammed Eissa'),
    ('hamadatarek045@gmail.com', 'Ahmed Tarek'),
    ('hamidaammar870@gmail.com', 'Ammar Hamida'),
    ('hamidelsadig23@gmail.com', 'Hamid'),
    ('hamidelsadig25@gmail.com', 'hamid elsadig'),
    ('hammamgouda7@gmail.com', 'hammam abdelgelil abdelkarim gouda'),
    ('hamodi321@icloud.com', None),
    ('hamzainm89@gmail.com', 'yourname@gmail.co'),
    ('hand.media.ads@gmail.com', 'Ahmed'),
    ('haneenmashehata@gmail.com', 'Haneen mohamed ahmed shehata'),
    ('hanosh5180@gmail.com', 'Hana Ahmed'),
    ('hayaazab8@gmail.com', 'hayaazab'),
    ('hema01973@gmail.com', 'Ibrahim Ali Ibrahim'),
    ('heshamabbaswork1028@gmail.com', 'Hesham El Shafie'),
    ('hm8087022@gmail.com', 'Hisham Mohammad'),
    ('hmerawem@gmail.com', 'Haithem Merawem'),
    ('hodaelewa99@gmail.com', 'hoda elewa'),
    ('hossam.programs@outlook.com', 'Hossam Eldin Ouda'),
    ('hozifacf5@gmail.com', 'Ahmed Abass'),
    ('ib2945585@gmail.com', 'Gamal Abd Elhady'),
    ('ibrahemmostfasuidahamed@gmail.com', 'Ibrahem-Mostfa'),
    ('info2hazemmohamed@gmail.com', 'Hazem Mohamed'),
    ('ismailhamdy1234@gmail.com', 'Ismail Hamdy'),
    ('iyadmohammed70@gmail.com', 'Iyad Mohammed elsayed Abbas'),
    ('jannamahmoud512@gmail.com', 'Jana mahmoud abouelezz'),
    ('jayor955@gmail.com', 'Alaa Sami'),
    ('jjyss4dnzx@privaterelay.appleid.com', 'YoussefElshazly'),
    ('jna98414@gmail.com', 'Jana Khaled'),
    ('judy.ramy4321@gmail.com', None),
    ('kaly0260@gmail.com', 'Kareem sameh mahmoud Aly'),
    ('kamalasaad1991@gmail.com', 'Kamal Asaad'),
    ('karasy305@gmail.com', None),
    ('karawansharqiah@gmail.com', None),
    ('kareem.tarek12211@gmail.com', 'kareem tarek'),
    ('kariemelgendy@gmail.com', 'kariem mohamed essam eldien'),
    ('karim.a.eldidi@gmail.com', None),
    ('karimhisham1210@gmail.com', 'Karim Hisham'),
    ('karimmohmoud7@gmail.com', 'Karim Mohmoud'),
    ('karimshady911@gmail.com', 'Karim Shady'),
    ('kerollosmagdy00@gmail.com', 'Kerollos Magdy'),
    ('khaled.o3111@yahoo.com', 'Omar khaled'),
    ('khaledstawfik@hotmail.com', 'Khaled'),
    ('khalilnadirhassan@gmail.com', 'Mohamed El monzer'),
    ('kheba2505@gmail.com', 'Heba Khaled'),
    ('khedrmahmoud392@gmail.com', 'Mahmoud Khedr'),
    ('kirolsksamiryb@gmail.com', 'Kirolos Shahat kahlifa'),
    ('komar7867@gmail.com', 'Omar Khaled Salaheldin'),
    ('leeb09313@gmail.com', 'Bruce Lee'),
    ('leloabdo955@gmail.com', 'Clara'),
    ('lilmerasoliman1@gmail.com', None),
    ('loaymohamed606@gmail.com', 'Loay Mohamed elsaied'),
    ('logym9393@gmail.com', 'Logy Mohamed Sayed'),
    ('lokaelgammal122@gmail.com', None),
    ('lwy952645@gmail.com', 'KHALED'),
    ('m.elsayed1803@gmail.com', 'Mohamed Elsayed Ragab Elreedy'),
    ('m7tdrt6shx@privaterelay.appleid.com', 'Abdullah Hegazy'),
    ('m92taz@gmail.com', 'Moataz'),
    ('maha.a.a.osman@gmail.com', 'Maha Osman'),
    ('mahmoud.abdallahh22@gmail.com', 'Maghraby'),
    ('mahmoud.sherpini@gmail.com', 'Mahmoud Sherpini'),
    ('mahmoudahmed1928n@gmail.com', None),
    ('mahmoudelbakh582@gmail.com', 'Mahmoud elbakh'),
    ('mahmoudgmal700@gmail.com', 'Mahmoud Gmal Abdelrehem'),
    ('mahmoudhesham7763@gmail.com', 'Mahmoud Abdallah'),
    ('mahmoudmostfa745@gmail.com', 'محمود مصطفى'),
    ('mahmouds011224268847@gmail.com', None),
    ('mahmoudspeedo40@gmail.com', 'MahmoudHooda'),
    ('maicandles2@gmail.com', 'Mai Hossam'),
    ('maii.abdelkarim304@gmail.com', 'Eman Sabry'),
    ('malekdawoodd@gmail.com', 'Malek'),
    ('malekelgammaal@gmail.com', 'Malek Elgammal'),
    ('mariamelshihawy716@gmail.com', None),
    ('mariamwael742007@gmail.com', 'Mariam Wael'),
    ('mariaremosedky@gmail.com', 'Maria Remon Sedky Dawood Khalil'),
    ('mark.gouda.farah@gmail.com', 'Marc Spencer'),
    ('markrokakoko@gmail.com', 'Mark'),
    ('marmora5123@gmail.com', 'marina amir'),
    ('marqiooomor@gmail.com', 'Mario morcos'),
    ('marwan.sbiiika@icloud.com', 'Marwan sbika'),
    ('mazen.elteer123@gmail.com', 'Mazen Mohamed Farouk Mohamed Elteer'),
    ('mazenmo906@gmail.com', None),
    ('mazennawar10@gmail.com', 'mazen awar'),
    ('mazenramy6oct@gmail.com', 'Mazen Ramy'),
    ('mazenssam3@gmail.com', 'Mazen Essam'),
    ('mdinahassan1999@gmail.com', 'Dina hassan'),
    ('medo122e@gmail.com', 'DR-MO'),
    ('megomohamedninja@gmail.com', 'Mohamed Khaled'),
    ('melmatmohamed@gmail.com', 'Mohamed Melmat'),
    ('mennaaro@gmail.com', 'Menna osman'),
    ('mennaelgazar812@gmail.com', 'menna elgazar'),
    ('mero.com821@gmail.com', 'Ammar yasser Elmesallamy'),
    ('mh143100@gmail.com', 'Mohamed Hossam'),
    ('mhmedmahmoud213@icloud.com', 'Mhmed'),
    ('mhmudera@gmail.com', 'mahmoud Attia'),
    ('minaamir1217@gmail.com', 'Mina Amir'),
    ('minagorg741@gmail.com', 'Mina George'),
    ('mkea6197661@gmail.com', 'Mahmoud Mohamed'),
    ('mm.salah937@gmail.com', 'Mazen Mahmoud Salah'),
    ('mm8202470@gmail.com', 'Mohamed Araby'),
    ('mmmanan84@gmail.com', 'Mohamed Anan'),
    ('mmna33221@gmail.com', 'Mostafa Nour'),
    ('mmohamedsayed7811@gmail.com', 'Mohamed Sayed'),
    ('mo7amad.osama.29@gmail.com', 'Mohamed osama'),
    ('moatazahmed737@gmail.com', 'moatazzo0'),
    ('moaz.khaled10@gmail.com', 'Moaz Khaled'),
    ('moaz.shaker2021@gmail.com', 'Moaz Mohamed Shaker'),
    ('moazh3109@gmail.com', 'Moaz mohamed'),
    ('moh.sherif2777@gmail.com', 'Mohamed Sherif'),
    ('mohaad11@icloud.com', 'Moaz Belfkih'),
    ('mohamed.kamal20100@gmail.com', 'Youssef mohamed kamal'),
    ('mohamed.mehrez@gmail.com', 'Mohamed youssef soliman Mehrez'),
    ('mohamed3zma77@gmail.com', 'Mohamed Ahmed'),
    ('mohamedabdelllatif1@gmail.com', 'Mohamed Abdellatif'),
    ('mohamedahmed243171@gmail.com', 'Mohamed'),
    ('mohamedamrahmed2005@gmail.com', 'Mohamed Amr'),
    ('mohamedatia16max@gmail.com', 'Mohamed Attia mohamed essia'),
    ('mohamedattia30881@gmail.com', 'Mohamed Attia'),
    ('mohamedd.salah21@gmail.com', 'Mohamed Salah'),
    ('mohamedelsay3d0@gmail.com', 'MOhamed ELsayed'),
    ('mohamedhashem1995@gmail.com', 'Mohamed Hashem'),
    ('mohamedhassanr18@gmail.com', 'Mohamed Hassan Mohamed'),
    ('mohamedhazem20052005@gmail.com', 'Mohamed Hazem'),
    ('mohamedhoag99@gmail.com', 'Mohamed Hossam Attia Aglan'),
    ('mohamedkhaledpro23122@gmail.com', 'Mohamed Khaled'),
    ('mohamedmabd183@gmail.com', None),
    ('mohamednaserdesouky@gmail.com', 'Mohamed Nasser Desouky'),
    ('mohamednourbeef0@gmail.com', 'mohamed nour beef'),
    ('mohamedrawhy4030@gmail.com', 'Mohamed Rawhy'),
    ('mohamedselim14286@gmail.com', 'mohamedselim'),
    ('mohamepxd@gmail.com', 'mohammed mamdouh'),
    ('mohammadsafwat479@gmail.com', 'Mohamed Safwat'),
    ('mohcr7392@gmail.com', 'Mohamed Ashraf'),
    ('monamhossam93@gmail.com', 'Hossam eldin abdelmeniam'),
    ('monamohsen529@gmail.com', 'Mona Lisa'),
    ('monzerlearning@gmail.com', 'Monzer Abdelgawad'),
    ('mooaboelezz74@gmail.com', 'Mohamed aboelezz'),
    ('mostafa.mahmoud.bui@gmail.com', 'Mostafa Mahmoud'),
    ('mostafa.nonne@gmail.com', 'Mostafa'),
    ('mostafaahmed01099394013@gmail.com', 'mostafaahmed6c'),
    ('mostafabadawi48@gmail.com', 'Mostafa Badawi'),
    ('mostafakamel122000@gmail.com', 'Mostafa Kamel'),
    ('mostafalotfy28social@gmail.com', 'Mostafa AlTayeb'),
    ('mostafamunir7@gmail.com', 'Moustafa Munir'),
    ('mostfamohammedrgab@gmail.com', 'mostfa mohammed'),
    ('mrhaboula@gmail.com', 'Omar Khaled Haboula'),
    ('ms1963710@gmail.com', 'Mariam Sameh'),
    ('msm4allgpt@gmail.com', 'Mohamed Saeed Mohamed Ali'),
    ('mstfymhmwdmstfy856@gmail.com', 'Mostafa mahmoud'),
    ('mtifa58@gmail.com', 'mustafa ashraf'),
    ('muhamedhanyy0099@gmail.com', 'muhamedhanyy'),
    ('muhammad.awwad.077@gmail.com', 'Mohamed Awwad'),
    ('muhammedabdelghanii@gmail.com', 'Mohamed Abdelghany'),
    ('mustafakhaled6663@gmail.com', 'Moustafa Khaled'),
    ('mwaled507@gmail.com', 'Mohamed Waleed'),
    ('mynashhat51@gmail.com', 'mina shahat khalifa'),
    ('nabil.ahmed123x@gmail.com', None),
    ('nada.ahmedgomaa112@gmail.com', 'nada ahmed'),
    ('nadabdlali@gmail.com', 'Nada Abdali'),
    ('nahl_6@yahoo.com', 'Nahla'),
    ('nairaosama563@gmail.com', 'Naira Osama'),
    ('nana6720016@gmail.com', 'Safia Ameen'),
    ('nirmenahmed97@gmail.com', 'Nirmen Ahmed'),
    ('nodassad@gmail.com', 'Hondaaa'),
    ('nouranbackup17@gmail.com', 'Nouran Saad'),
    ('novasparkle43@gmail.com', 'Youssef Gamal Foud Abdelrahim'),
    ('oelshazli22@gmail.com', 'oelshazli'),
    ('officialahmedmedhat@gmail.com', 'Ahmed medhat'),
    ('ohood.alhousani@gmail.com', 'Ohood Ali'),
    ('om1332008@gmail.com', 'Omar'),
    ('om3716030@gmail.com', 'Omar shawky'),
    ('om7515979@gmail.com', 'omar mohamed'),
    ('omar.elqabbany@gmail.com', 'Omar Mahmoud'),
    ('omar15.mohammed8.8@gmail.com', 'Omar alsaadi'),
    ('omar2006hamza@gmail.com', None),
    ('omaradel1332008@icloud.com', 'omaradel89'),
    ('omarahmed363d@gmail.com', 'omar ahmed shawky'),
    ('omaraldly20@gmail.com', 'omaraldly'),
    ('omarashraftaha19@gmail.com', None),
    ('omarcodemokhtar@gmail.com', 'Omar Mokhtar abdelrahman ibrahim'),
    ('omarelbialy@gmail.com', 'Omar elbialy'),
    ('omarelfeky_98@hotmail.com', 'Omar elfeky'),
    ('omaremadd111@gmail.com', 'Omar Emad'),
    ('omarfawaz2003.2016@gmail.com', 'Omar Fawaz'),
    ('omarmohamed.official02@gmail.com', 'Omar Kamel'),
    ('omarzzz579@gmail.com', 'Omar Ayyad'),
    ('omradasolo@gmail.com', 'Alaa Hamid'),
    ('omralhrawy@gmail.com', 'Omar elharawy'),
    ('parpershopgiga@gmail.com', 'عبدالرحمن ابوطريه'),
    ('parthinianessim@gmail.com', 'Parthinia'),
    ('pdgpjx9292@privaterelay.appleid.com', 'Youssef Ali'),
    ('podytamer22@gmail.com', 'pody tamer'),
    ('q8202445@gmail.com', None),
    ('qjqwfxxf7g@privaterelay.appleid.com', 'osama marawan ali'),
    ('rababhosny065@gmail.com', 'Rabab Hosny Mostafa Ahmed'),
    ('rabie.r112233@gmail.com', 'Ahmed Rabie'),
    ('ragabkareem878@gmail.com', 'Kareem Ragab'),
    ('rami.alaa-eldin@outlook.com', 'Ramy Alaa'),
    ('ramy.wadina@gmail.com', 'Ramy Saadedin marzook zaied'),
    ('rana.gamal905@gmail.com', 'Rana gamal'),
    ('raneya-mohamed@hotmail.com', 'Raneya Mohamed'),
    ('raniamoustafa288@gmail.com', None),
    ('raniamoustafa307@gmail.com', 'Rania Moustafa'),
    ('ranooshshedid@gmail.com', 'Rana'),
    ('raoufmohammeda@gmail.com', 'AbdelRaouf Mohammed'),
    ('rebrahemelbadry@gmail.com', 'Rewan Ebrahim'),
    ('remon.u.marzok@gmail.com', None),
    ('rnda.zakarya@gmail.com', 'Randa Zakaria'),
    ('rokiakotb7@gmail.com', None),
    ('rumashrmajhjji@gmail.com', 'Mohamed Abudaiff'),
    ('rwmanybshay9@gmail.com', 'romany abdelshahid'),
    ('s01122426847@gmail.com', 'MAHMOUD ELETR'),
    ('sadenkhaledmohamedabdo@gmail.com', 'Saden Khaled'),
    ('saeedalo851@gmail.com', 'Saed Essam abdelmaabod ali'),
    ('sahoma4434@gmail.com', None),
    ('saif98mohamed77@gmail.com', 'Seif mohamed'),
    ('sakr66703@gmail.com', 'Abdoman'),
    ('salmakassem6@gmail.com', 'Salma Mohamed'),
    ('salmamansour022@gmail.com', 'Salma Ayman mansour'),
    ('saraab331@protonmail.com', 'Sarab abd el khalik'),
    ('sayedayman1810@gmail.com', None),
    ('seif.personal18@gmail.com', 'Seif elden adel ahmed foud'),
    ('seif01062433721@gmail.com', 'Seif Nabil abdelkahlik'),
    ('seifeldeenembaby@gmail.com', 'Seif Embaby'),
    ('sh3011761@gmail.com', 'Sama Hassan'),
    ('shehabhany2014@gmail.com', 'Shehab Hany'),
    ('sherinhossam7@gmail.com', 'Sherin Hossam'),
    ('shesmaal4444@gmail.com', 'Mahmoud Ahmed'),
    ('shimaaelsayed891@gmail.com', 'shimaaelsayed891@gmailcom'),
    ('shmshshow@gmail.com', 'Habiba Elshowehdy'),
    ('shokr821@gmail.com', 'Mohamed Shokr'),
    ('silenttwraith@gmail.com', 'Mohamed Khaled Sayed'),
    ('skoskosko121@gmail.com', 'Muhammad Ashraf'),
    ('slamhmadhadl@gmail.com', 'Moaz Adel Salama'),
    ('sleem.star6764@gmail.com', 'Mahmoud Sleem'),
    ('sleembanoub70@gmail.com', 'Seleem banoub'),
    ('solimanomar011@gmail.com', 'Omar Ahmed Soliman'),
    ('son.n8n@gmail.com', None),
    ('sotaher45@gmail.com', 'Sohaila Taher'),
    ('ssarahijazi@gmail.com', 'Sara Hijazi'),
    ('ssaratrials@gmail.com', 'Sara trials'),
    ('t92alal@gmail.com', 'Talal'),
    ('tarhgf359@gmail.com', 'ABDALLAH Khalid'),
    ('tassneemmohamad@gmail.com', 'Tassnem Mohamed'),
    ('teamaomar82@yahoo.com', 'Nagwan'),
    ('thedemetry66@gmail.com', 'fady demetry'),
    ('twngy2002@gmail.com', 'Ahmed mohamed abdelmeneam'),
    ('uuuuyiii8@gmail.com', 'Othman'),
    ('wbdalwahd50@gmail.com', 'Walid Mohamed Abdelwahid'),
    ('wekenzi1995@gmail.com', 'Mohamed Khaled'),
    ('whopbusines1@gmail.com', 'Mohamed Said'),
    ('wjqf9btgg4@privaterelay.appleid.com', 'Mohamed Nasser'),
    ('xxxomar.ahmed.2024@gmail.com', 'Omar Ahmed'),
    ('y.abdelwahab110@gmail.com', None),
    ('ya064321@gmail.com', 'Yassin Ahmed'),
    ('yarahossam331@gmail.com', 'Yara Hossam'),
    ('yasmin.reda2010@gmail.com', 'Yasmin Reda'),
    ('yassiinn2099@gmail.com', 'Yasen Jamal'),
    ('yassinazmy12@gmail.com', 'Yassin azmy'),
    ('yassinetahri109@gmail.com', None),
    ('ymtawfik04@gmail.com', 'Youssef Tawfik'),
    ('yomnayoussef1@gmail.com', 'Yomna Youssef'),
    ('yossefahmed50@gmail.com', 'Youssef Ahmed'),
    ('yousefahmed1052009@gmail.com', 'yousef ahmed'),
    ('yousefayman060@gmail.com', 'Yousef ayman'),
    ('yousefelshishtawy30@gmail.com', 'yousefelshishtawy'),
    ('youseifmansour6@gmail.com', 'youssef mansouer'),
    ('youssef.egy321@gmail.com', 'zad'),
    ('youssef720020@gmail.com', 'Youssef Elsedeek'),
    ('youssefabary77@gmail.com', 'youssefabary'),
    ('youssefbassem@aucegypt.edu', 'Youssef Bassem Elfeky'),
    ('youssefkhaledgamal.8@gmail.com', 'youssef khaled gamal eldien gomaa'),
    ('youssefmohameddessouky@gmail.com', 'Youssef dessouky'),
    ('youssefmohammed.said.ds@gmail.com', 'Youssef'),
    ('youssfragab184@gmail.com', 'Youssef Ragab'),
    ('yoyoashraf2003@gmail.com', 'Yousef Ashraf'),
    ('yroro7935@gmail.com', 'Reham Ashraf Mostafa Yassen'),
    ('ys6849993@gmail.com', 'youssef elsherif'),
    ('ywael1333@gmail.com', 'Youssef Wael'),
    ('zahrafarghaly1@gmail.com', 'zahra'),
    ('zaineddinmohamedhassan@gmail.com', 'Zaineddin Mohamed Hassan'),
    ('zaivosamy@gmail.com', 'Ziad Samy'),
    ('zeyad1932002@gmail.com', None),
    ('zeyadossama94@gmail.com', None),
    ('zeyadtamer146@gmail.com', 'Zeyad Tamer'),
    ('zeyadz666@gmail.com', 'zeyad sallam'),
    ('zhawwsad@gmail.com', 'Zeyad hossam'),
    ('ziadabdelnasser21@gmail.com', 'ziad abdelnasser saad abdlrehem'),
    ('ziadfarag202@gmail.com', 'Ziad farag'),
    ('ziyadsaleh764@gmail.com', 'Ziyad Saleh'),
    ('zizomizo.allam@gmail.com', 'Bassel allam'),
    ('zxc50zxcc@gmail.com', 'mohamed'),
]


def upgrade() -> None:
    # Predates ghawy_baseline: on a database built from that snapshot this
    # change is already present, so there is nothing to apply.
    if baseline_created_schema():
        return
    conn = op.get_bind()

    op.add_column('legacy_emails', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('legacy_promo_round', sa.Integer(),
                                     server_default=sa.text('0'), nullable=False))

    # Everyone who redeemed round 1 is recorded as having spent round 1, so the
    # round check can tell them apart from someone who has spent nothing.
    conn.execute(sa.text(
        "UPDATE users SET legacy_promo_round = 1 WHERE is_legacy_redeemed IS TRUE"
    ))

    # Insert what is missing, and fill in the name on rows that already exist.
    # ON CONFLICT keeps this re-runnable and keeps the insert from tripping over
    # the unique index on email.
    conn.execute(
        sa.text("""
            INSERT INTO legacy_emails (email, full_name)
            VALUES (:email, :full_name)
            ON CONFLICT (email) DO UPDATE
               SET full_name = COALESCE(EXCLUDED.full_name, legacy_emails.full_name)
        """),
        [{"email": e, "full_name": n} for e, n in ATLAS_ROSTER],
    )

    # Drop the misspellings. The NOT EXISTS guard is what makes running a DELETE
    # against production defensible rather than merely argued: nobody can have
    # redeemed against an address that is nobody's, so the guard should match
    # nothing — and if it ever does match, that row stays and we look at it
    # instead of losing it.
    conn.execute(
        sa.text("""
            DELETE FROM legacy_emails
             WHERE email NOT IN :roster
               AND NOT EXISTS (SELECT 1 FROM users u
                                WHERE lower(u.email) = legacy_emails.email
                                  AND (u.is_legacy_redeemed IS TRUE
                                       OR u.legacy_promo_round > 0))
        """).bindparams(sa.bindparam("roster", expanding=True)),
        {"roster": [e for e, _ in ATLAS_ROSTER]},
    )


def downgrade() -> None:
    # Predates ghawy_baseline: on a database built from that snapshot this
    # change is already present, so there is nothing to apply.
    if baseline_created_schema():
        return
    # The rows are deliberately left alone. Re-inserting the 171 misspellings
    # would be restoring the corruption this migration exists to remove, and the
    # addresses it added are real members either way.
    op.drop_column('users', 'legacy_promo_round')
    op.drop_column('legacy_emails', 'full_name')
