"""remove recurring and add end_at

Revision ID: aaa10e9ec801
Revises: 4823c6c0b288
Create Date: 2026-06-12 01:23:15.674665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aaa10e9ec801'
down_revision: Union[str, Sequence[str], None] = '4823c6c0b288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_chat_message_reaction'), 'chat_message_reactions', type_='unique')
    op.create_unique_constraint('uq_chat_message_reaction_user', 'chat_message_reactions', ['message_id', 'user_id'])
    op.drop_column('payments', 'recurring_cycle')
    op.drop_column('payments', 'is_recurring')
    op.alter_column('project_submissions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'CHANGES_REQUESTED', name='projectsubmissionstatus'),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('users', sa.Column('end_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'failed_charge_count')
    op.drop_column('users', 'subscription_end')
    op.drop_column('users', 'last_charged_at')
    op.drop_column('users', 'card_token')
    op.drop_column('users', 'shopper_reference')
    op.drop_column('users', 'next_charge_at')
    op.drop_column('users', 'subscription_type')
    op.drop_column('users', 'ccv_token')
    op.drop_column('users', 'subscription_start')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('ccv_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('subscription_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('next_charge_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('shopper_reference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('card_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_charged_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('subscription_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('failed_charge_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_column('users', 'end_at')
    op.alter_column('project_submissions', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PENDING', 'APPROVED', 'CHANGES_REQUESTED', name='projectsubmissionstatus'),
               existing_nullable=False)
    op.add_column('payments', sa.Column('is_recurring', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('recurring_cycle', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_chat_message_reaction_user', 'chat_message_reactions', type_='unique')
    op.create_unique_constraint(op.f('uq_chat_message_reaction'), 'chat_message_reactions', ['message_id', 'user_id', 'emoji'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
