"""add video progress and markers

Revision ID: e478012af2b4
Revises: f1201efadb0f
Create Date: 2026-05-30 21:27:38.941183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from migration_utils import baseline_created_schema


# revision identifiers, used by Alembic.
revision: str = 'e478012af2b4'
down_revision: Union[str, Sequence[str], None] = 'f1201efadb0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Predates ghawy_baseline: on a database built from that snapshot this
    # change is already present, so there is nothing to apply.
    if baseline_created_schema():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('markers', sa.JSON(), nullable=True))
    op.add_column('user_progress', sa.Column('current_time', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.0'), nullable=True))
    op.add_column('user_progress', sa.Column('watched_percent', sa.Numeric(precision=5, scale=2), server_default=sa.text('0.0'), nullable=True))
    op.add_column('user_progress', sa.Column('is_completed', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('user_progress', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Predates ghawy_baseline: on a database built from that snapshot this
    # change is already present, so there is nothing to apply.
    if baseline_created_schema():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_progress', 'updated_at')
    op.drop_column('user_progress', 'is_completed')
    op.drop_column('user_progress', 'watched_percent')
    op.drop_column('user_progress', 'current_time')
    op.drop_column('lessons', 'markers')
    # ### end Alembic commands ###
