"""add user_progress and certificates

Revision ID: f1201efadb0f
Revises: ec6b20b59525
Create Date: 2026-05-30 19:27:23.178892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from migration_utils import baseline_created_schema
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1201efadb0f'
down_revision: Union[str, Sequence[str], None] = 'ec6b20b59525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Predates ghawy_baseline: on a database built from that snapshot this
    # change is already present, so there is nothing to apply.
    if baseline_created_schema():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_records_id'), table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_index(op.f('ix_guests_slug'), table_name='guests')
    op.drop_column('guests', 'deleted_at')
    op.drop_column('guests', 'is_published')
    op.drop_column('guests', 'slug')
    op.drop_column('guests', 'image_url')
    op.drop_column('guests', 'updated_at')
    op.drop_column('guests', 'is_deleted')
    op.drop_column('guests', 'sort_order')
    op.drop_column('guests', 'short_bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Predates ghawy_baseline: on a database built from that snapshot this
    # change is already present, so there is nothing to apply.
    if baseline_created_schema():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('short_bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('guests', sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('guests', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('guests', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('guests', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('guests', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('guests', sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('guests', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_guests_slug'), 'guests', ['slug'], unique=True)
    op.create_table('audit_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_metadata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('audit_records_actor_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_records_pkey'))
    )
    op.create_index(op.f('ix_audit_records_id'), 'audit_records', ['id'], unique=False)
    # ### end Alembic commands ###
